server:
  servlet:
    context-path: /poll
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://poll_db:5432/poll
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
logging:
  level:
    org.springframework:
      jdbc:
        core:
          JdbcTemplate: debug
